/**
 * Dependency-free smoke test for the pure-logic pieces: storage->markdown,
 * markdown->ADF, ADF->markdown, page-id extraction, and the push planner's
 * idempotency decisions. Runs without VS Code and without network.
 *
 *   node scripts/smoke.mjs
 */
import * as esbuild from 'esbuild';
import { writeFileSync, mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { createRequire } from 'node:module';
import path from 'node:path';

const dir = mkdtempSync(path.join(tmpdir(), 'reqforge-smoke-'));
const entry = path.join(dir, 'entry.mjs');

writeFileSync(
  entry,
  `
export { storageToMarkdown } from '${path.resolve('src/adapters/atlassian/storageFormat.ts')}';
export { markdownToAdf, adfToMarkdown } from '${path.resolve('src/adapters/atlassian/adf.ts')}';
export { extractPageId } from '${path.resolve('src/adapters/atlassian/rest.ts')}';
export { epicToMarkdown, stampLabel, epicFingerprint } from '${path.resolve('src/core/model.ts')}';
export { serializeBacklog, deserializeBacklog } from '${path.resolve('src/core/store.ts')}';
export { evaluateBacklog, scoreCriteria, fixInstruction, cacheKey } from '${path.resolve('src/core/rubric/score.ts')}';
export { DEFAULT_RUBRIC } from '${path.resolve('src/core/rubric/types.ts')}';
export { RULE_IDS } from '${path.resolve('src/core/rubric/rules.ts')}';
export { STORY_CRITERIA, EPIC_CRITERIA } from '${path.resolve('src/core/rubric/criteria.ts')}';
`
);

// CJS, matching how the extension itself is bundled: some deps (yaml) are CJS
// and cannot be dynamically required from an ESM bundle.
const out = path.join(dir, 'bundle.cjs');
await esbuild.build({
  entryPoints: [entry],
  bundle: true,
  outfile: out,
  platform: 'node',
  format: 'cjs',
  logLevel: 'error'
});

const m = createRequire(import.meta.url)(out);

let pass = 0;
let fail = 0;
const check = (name, cond, detail = '') => {
  if (cond) {
    pass++;
    console.log(`  ok    ${name}`);
  } else {
    fail++;
    console.log(`  FAIL  ${name}${detail ? `\n        ${detail}` : ''}`);
  }
};

/* ------------------------------------------------ confluence storage format */

const storage = `
<h1>Payments Revamp</h1>
<p>We need to <strong>reduce</strong> checkout friction.</p>
<ac:structured-macro ac:name="info"><ac:rich-text-body><p>Deadline is Q3.</p></ac:rich-text-body></ac:structured-macro>
<h2>Requirements</h2>
<ul><li>Support Apple Pay</li><li>Support saved cards</li></ul>
<table><tbody>
<tr><th>Field</th><th>Rule</th></tr>
<tr><td>Amount</td><td>Must be positive</td></tr>
</tbody></table>
<ac:structured-macro ac:name="code"><ac:plain-text-body><![CDATA[POST /v1/charge]]></ac:plain-text-body></ac:structured-macro>
<ac:task-list><ac:task><ac:task-id>1</ac:task-id><ac:status>complete</ac:status><ac:task-body>Legal review</ac:task-body></ac:task></ac:task-list>
`;

const md = m.storageToMarkdown(storage);
check('storage: heading survives', md.includes('# Payments Revamp'), md.slice(0, 200));
check('storage: bold survives', md.includes('**reduce**'));
check('storage: info macro body survives', md.includes('Deadline is Q3'));
check('storage: list survives', md.includes('- Support Apple Pay'));
check('storage: table becomes a markdown table', md.includes('| Field | Rule |'), md);
check('storage: code macro survives', md.includes('POST /v1/charge'));
check('storage: task body survives', md.includes('Legal review'));
check('storage: no raw ac: tags leak through', !md.includes('<ac:'), md);

/* --------------------------------------------------------- markdown <-> ADF */

const source = [
  '*Outcome:* Faster checkout',
  '',
  '## In scope',
  '- Apple Pay',
  '- Saved cards',
  '',
  '## Acceptance criteria',
  '- **Given** a saved card **when** the user checks out **then** no re-entry is required',
  '',
  '```ts',
  'const x = 1;',
  '```',
  '',
  'See [the spec](https://example.com/spec).',
  '',
  '---',
  '_Generated by ReqForge._'
].join('\n');

const adf = m.markdownToAdf(source);
check('adf: is a doc', adf.type === 'doc' && adf.version === 1);
check('adf: has heading nodes', adf.content.some((n) => n.type === 'heading'));
check('adf: has bullet list', adf.content.some((n) => n.type === 'bulletList'));
check('adf: has code block', adf.content.some((n) => n.type === 'codeBlock'));
check('adf: has rule', adf.content.some((n) => n.type === 'rule'));

const codeBlock = adf.content.find((n) => n.type === 'codeBlock');
check('adf: code block keeps language', codeBlock?.attrs?.language === 'ts', JSON.stringify(codeBlock));
check('adf: code block keeps content', codeBlock?.content?.[0]?.text === 'const x = 1;');

const flat = JSON.stringify(adf);
check('adf: link mark emitted', flat.includes('"type":"link"') && flat.includes('https://example.com/spec'));
check('adf: strong mark emitted', flat.includes('"type":"strong"'));
check('adf: no empty text nodes', !flat.includes('"text":""'), 'empty text nodes are rejected by Jira');

const roundTrip = m.adfToMarkdown(adf);
check('adf round trip: keeps heading', roundTrip.includes('## In scope'));
check('adf round trip: keeps list item', roundTrip.includes('- Apple Pay'));
check('adf round trip: keeps link', roundTrip.includes('[the spec](https://example.com/spec)'));

check('adf: empty input still produces a valid doc', m.markdownToAdf('').content.length > 0);

/* ------------------------------------------------------------ page id parse */

check('pageId: bare id', m.extractPageId('123456') === '123456');
check(
  'pageId: modern url',
  m.extractPageId('https://acme.atlassian.net/wiki/spaces/PROD/pages/98765/My+PRD') === '98765'
);
check('pageId: legacy url', m.extractPageId('https://acme.atlassian.net/wiki/pages/viewpage.action?pageId=555') === '555');
let threw = false;
try {
  m.extractPageId('not-a-page');
} catch {
  threw = true;
}
check('pageId: rejects nonsense with a clear error', threw);

/* ------------------------------------------------------- model + serialization */

const epic = {
  ref: 'apple-pay',
  title: 'Apple Pay at checkout',
  outcome: 'Shoppers can pay without typing card details',
  description: 'Body text.',
  inScope: ['iOS Safari'],
  outOfScope: ['Android'],
  acceptanceCriteria: [{ given: 'a device with Apple Pay', when: 'the user checks out', then: 'the sheet appears' }],
  dependsOn: [],
  sizing: 'M',
  openQuestions: ['Which PSP?'],
  sourceEvidence: ['reduce checkout friction']
};

const epicMd = m.epicToMarkdown(epic);
check('epic markdown: has outcome', epicMd.includes('Faster'.length ? 'Outcome:' : ''));
check('epic markdown: has AC section', epicMd.includes('## Acceptance criteria'));
check('epic markdown: has out of scope', epicMd.includes('## Out of scope'));
check('epic markdown: converts cleanly to ADF', m.markdownToAdf(epicMd).content.length > 5);

check('stamp label is JQL-safe', /^[A-Za-z0-9_-]+$/.test(m.stampLabel('12345', 'apple-pay')));
check('stamp label is stable', m.stampLabel('12345', 'apple-pay') === m.stampLabel('12345', 'apple-pay'));
check(
  'fingerprint changes when content changes',
  m.epicFingerprint(epic) !== m.epicFingerprint({ ...epic, title: 'Different' })
);
check('fingerprint is stable across identical objects', m.epicFingerprint(epic) === m.epicFingerprint({ ...epic }));

const backlog = {
  version: 1,
  source: { kind: 'confluence', pageId: '1', title: 'T', url: 'u', ingestedAt: 'now' },
  target: { projectKey: 'ACME', epicIssueType: 'Epic', storyIssueType: 'Story' },
  prd: { title: 'T', summary: 's', goals: [], nonGoals: [], personas: [], constraints: [], openQuestions: [], risks: [] },
  epics: [{ ...epic, sync: {}, stories: [] }]
};

const yaml = m.serializeBacklog(backlog);
const back = m.deserializeBacklog(yaml);
check('backlog round trips through yaml', back.epics[0].ref === 'apple-pay' && back.target.projectKey === 'ACME');
check('backlog yaml carries the editing header', yaml.startsWith('# ReqForge backlog'));

let versionRejected = false;
try {
  m.deserializeBacklog('version: 99\n');
} catch {
  versionRejected = true;
}
check('backlog rejects an unknown schema version', versionRejected);

/* ------------------------------------------- hand-edited files must survive */

// Regression: a hand-edited backlog that omits optional lists used to load as
// undefined and then throw "Cannot read properties of undefined (reading
// 'length')" from inside epicToMarkdown, at push time.
const handEdited = `
version: 1
source: {kind: confluence, pageId: "1", title: T, url: u, ingestedAt: now}
target: {projectKey: ACME}
prd: {title: T, summary: s}
epics:
  - ref: minimal
    title: An epic with every optional field removed
    outcome: Something useful happens
    description: Body.
    stories:
      - ref: minimal-story
        epicRef: minimal
        title: A story with no optional fields
        narrative: {asA: user, iWant: a thing, soThat: a benefit}
        acceptanceCriteria:
          - {given: g, when: w, then: t}
`;

let loaded;
try {
  loaded = m.deserializeBacklog(handEdited);
  check('hand-edited backlog loads', true);
} catch (err) {
  check('hand-edited backlog loads', false, err.message);
}

if (loaded) {
  const e = loaded.epics[0];
  check('missing lists default to []', Array.isArray(e.inScope) && Array.isArray(e.acceptanceCriteria));
  check('missing sync defaults to {}', e.sync && typeof e.sync === 'object' && !e.sync.jiraKey);
  check('missing issue types default', loaded.target.epicIssueType === 'Epic' && loaded.target.storyIssueType === 'Story');
  check('missing prd lists default to []', Array.isArray(loaded.prd.goals) && Array.isArray(loaded.prd.openQuestions));
  try {
    const rendered = m.epicToMarkdown(e);
    check('minimal epic renders without throwing', rendered.includes('Something useful happens'));
    check('minimal epic renders to valid ADF', m.markdownToAdf(rendered).content.length > 0);
  } catch (err) {
    check('minimal epic renders without throwing', false, err.message);
  }
}

// A genuinely broken file must say which field is wrong, not throw a TypeError.
let msg = '';
try {
  m.deserializeBacklog('version: 1\nsource: {kind: confluence, pageId: "1", title: T, url: u, ingestedAt: n}\ntarget: {projectKey: A}\nprd: {title: T, summary: s}\nepics: [{ref: "Bad Ref!", title: x, outcome: y, description: z}]\n');
} catch (err) {
  msg = err.message;
}
check('invalid field is reported with its path', msg.includes('epics.0.ref'), msg);

/* ------------------------------------------------------------------ rubric */

const goodStory = {
  ref: 'good-story',
  epicRef: 'good',
  title: 'Show saved cards at checkout',
  narrative: {
    asA: 'returning shopper',
    iWant: 'to see the cards I have saved',
    soThat: 'I can complete payment without finding my wallet'
  },
  description: '',
  acceptanceCriteria: [{ given: 'a shopper with two saved cards', when: 'the checkout page loads', then: 'both cards are listed' }],
  points: 3,
  openQuestions: [],
  sync: {}
};

const goodEpic = {
  ref: 'good',
  title: 'Saved cards at checkout',
  outcome: 'Returning shoppers pay without re-entering card details',
  description: 'Body.',
  inScope: ['iOS Safari'],
  outOfScope: ['Android'],
  acceptanceCriteria: [{ given: 'a saved card', when: 'the shopper checks out', then: 'no re-entry is required' }],
  dependsOn: [],
  sizing: 'M',
  openQuestions: [],
  sourceEvidence: ['reduce checkout friction'],
  sync: {},
  stories: [goodStory]
};

const backlogOf = (epics) => ({
  version: 1,
  source: { kind: 'confluence', pageId: '1', title: 'T', url: 'u', ingestedAt: 'now' },
  target: { projectKey: 'ACME', epicIssueType: 'Epic', storyIssueType: 'Story' },
  prd: { title: 'T', summary: 's', goals: [], nonGoals: [], personas: [], constraints: [], openQuestions: [], risks: [] },
  epics
});

const findingsFor = (backlog, ref) => {
  const q = m.evaluateBacklog(backlog, m.DEFAULT_RUBRIC);
  const item = q.items.find((i) => i.ref === ref);
  return [...item.blockedBy, ...item.warnings].map((f) => f.ruleId);
};

check('rubric: a clean epic produces no blockers or warnings', (() => {
  const ids = findingsFor(backlogOf([goodEpic]), 'good');
  return ids.length === 0;
})(), JSON.stringify(findingsFor(backlogOf([goodEpic]), 'good')));

check('rubric: a clean story produces no blockers or warnings',
  findingsFor(backlogOf([goodEpic]), 'good-story').length === 0,
  JSON.stringify(findingsFor(backlogOf([goodEpic]), 'good-story')));

// Each of these must fire, or the rule is dead code.
const epicCases = [
  ['has-outcome', { ...goodEpic, outcome: '  ' }],
  ['has-acceptance-criteria', { ...goodEpic, acceptanceCriteria: [] }],
  ['complete-acceptance-criteria', { ...goodEpic, acceptanceCriteria: [{ given: 'x', when: '', then: 'y' }] }],
  ['dependencies-resolve', { ...goodEpic, dependsOn: ['nope'] }],
  ['no-self-dependency', { ...goodEpic, dependsOn: ['good'] }],
  ['has-evidence', { ...goodEpic, sourceEvidence: [] }],
  ['has-out-of-scope', { ...goodEpic, outOfScope: [] }],
  ['sizing-xl', { ...goodEpic, sizing: 'XL' }],
  ['no-stories', { ...goodEpic, stories: [] }],
  ['layer-shaped', { ...goodEpic, title: 'The payments API' }],
  ['vague-acceptance-criteria', { ...goodEpic, acceptanceCriteria: [{ given: 'a card', when: 'it is used', then: 'it works properly' }] }],
  ['too-many-stories', { ...goodEpic, stories: Array.from({ length: 13 }, (_, i) => ({ ...goodStory, ref: `s${i}` })) }]
];

for (const [ruleId, epic] of epicCases) {
  const ids = findingsFor(backlogOf([epic]), 'good');
  check(`rubric rule fires: ${ruleId}`, ids.includes(ruleId), `got: ${ids.join(', ') || '(none)'}`);
}

const storyCases = [
  ['has-narrative', { ...goodStory, narrative: { ...goodStory.narrative, soThat: '' } }],
  ['has-acceptance-criteria', { ...goodStory, acceptanceCriteria: [] }],
  ['generic-persona', { ...goodStory, narrative: { ...goodStory.narrative, asA: 'user' } }],
  ['too-large', { ...goodStory, points: 13 }],
  ['vague-acceptance-criteria', { ...goodStory, acceptanceCriteria: [{ given: 'a', when: 'b', then: 'it is user-friendly' }] }],
  ['benefit-restates-want', { ...goodStory, narrative: { asA: 'shopper', iWant: 'to see saved cards listed', soThat: 'saved cards are listed' } }]
];

for (const [ruleId, story] of storyCases) {
  const ids = findingsFor(backlogOf([{ ...goodEpic, stories: [story] }]), 'good-story');
  check(`rubric rule fires: ${ruleId} (story)`, ids.includes(ruleId), `got: ${ids.join(', ') || '(none)'}`);
}

/* scoring and gating */

const allThrees = m.STORY_CRITERIA.map((c) => ({ id: c.id, rating: 3, justification: 'x', suggestion: '' }));
const allZeros = m.STORY_CRITERIA.map((c) => ({ id: c.id, rating: 0, justification: 'x', suggestion: '' }));

check('score: all 3s is 100', m.scoreCriteria('story', allThrees, m.DEFAULT_RUBRIC) === 100);
check('score: all 0s is 0', m.scoreCriteria('story', allZeros, m.DEFAULT_RUBRIC) === 0);
check(
  'score: disabling a criterion does not cap the maximum',
  m.scoreCriteria('story', allThrees.filter((c) => c.id !== 'invest-testable'), {
    ...m.DEFAULT_RUBRIC,
    weights: { 'invest-testable': 0 }
  }) === 100
);
check(
  'score: unassessed criteria are excluded, not counted as zero',
  m.scoreCriteria('story', allThrees.slice(0, 2), m.DEFAULT_RUBRIC) === 100
);
check(
  'score: weighting Testable higher lowers the score when only Testable is poor',
  m.scoreCriteria('story', m.STORY_CRITERIA.map((c) => ({ id: c.id, rating: c.id === 'invest-testable' ? 0 : 3, justification: 'x', suggestion: '' })), m.DEFAULT_RUBRIC) < 80
);

// The gate: a blocker must fail an item no matter how well it scores.
const blocked = backlogOf([{ ...goodEpic, acceptanceCriteria: [] }]);
const cached = new Map([[m.cacheKey('epic', 'good', m.epicFingerprint({ ...goodEpic, acceptanceCriteria: [] })), m.EPIC_CRITERIA.map((c) => ({ id: c.id, rating: 3, justification: 'x', suggestion: '' }))]]);
const blockedQ = m.evaluateBacklog(blocked, m.DEFAULT_RUBRIC, cached);
const blockedItem = blockedQ.items.find((i) => i.ref === 'good');
check('gate: a perfect score still fails when a blocker fired', blockedItem.score === 100 && blockedItem.passed === false);

const cleanCached = new Map([[m.cacheKey('epic', 'good', m.epicFingerprint(goodEpic)), m.EPIC_CRITERIA.map((c) => ({ id: c.id, rating: 3, justification: 'x', suggestion: '' }))]]);
const cleanItem = m.evaluateBacklog(backlogOf([goodEpic]), m.DEFAULT_RUBRIC, cleanCached).items.find((i) => i.ref === 'good');
check('gate: a clean item at 100 passes', cleanItem.passed === true);

const lowCached = new Map([[m.cacheKey('epic', 'good', m.epicFingerprint(goodEpic)), m.EPIC_CRITERIA.map((c) => ({ id: c.id, rating: 1, justification: 'x', suggestion: '' }))]]);
const lowItem = m.evaluateBacklog(backlogOf([goodEpic]), m.DEFAULT_RUBRIC, lowCached).items.find((i) => i.ref === 'good');
check('gate: below threshold fails', lowItem.score < 70 && lowItem.passed === false);

check('gate: an unassessed item is not treated as passing', cleanItem.deterministicOnly === false &&
  m.evaluateBacklog(backlogOf([goodEpic]), m.DEFAULT_RUBRIC).items.find((i) => i.ref === 'good').passed === false);

// Editing an item must invalidate its cached assessment.
const edited = { ...goodEpic, title: 'A different title' };
const staleItem = m.evaluateBacklog(backlogOf([edited]), m.DEFAULT_RUBRIC, cleanCached).items.find((i) => i.ref === 'good');
check('cache: editing an item invalidates its assessment', staleItem.deterministicOnly === true);

check('fix instruction names the actual problems',
  m.fixInstruction(blockedItem).includes('No acceptance criteria'),
  m.fixInstruction(blockedItem));

check('rubric exposes every rule id for config', m.RULE_IDS.length >= 18 && m.RULE_IDS.includes('generic-persona'));
check('INVEST is complete and correctly named',
  ['Independent','Negotiable','Valuable','Estimable','Small','Testable'].every((n) => m.STORY_CRITERIA.some((c) => c.name === n)));

console.log(`\n${pass} passed, ${fail} failed`);
process.exit(fail === 0 ? 0 : 1);
