/**
 * Dependency-free smoke test for the pure-logic pieces: storage->markdown,
 * markdown->ADF, ADF->markdown, page-id extraction, and the push planner's
 * idempotency decisions. Runs without VS Code and without network.
 *
 *   node scripts/smoke.mjs
 */
import * as esbuild from 'esbuild';
import { writeFileSync, mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { createRequire } from 'node:module';
import path from 'node:path';

const dir = mkdtempSync(path.join(tmpdir(), 'reqforge-smoke-'));
const entry = path.join(dir, 'entry.mjs');

writeFileSync(
  entry,
  `
export { storageToMarkdown } from '${path.resolve('src/adapters/atlassian/storageFormat.ts')}';
export { markdownToAdf, adfToMarkdown } from '${path.resolve('src/adapters/atlassian/adf.ts')}';
export { extractPageId } from '${path.resolve('src/adapters/atlassian/rest.ts')}';
export { epicToMarkdown, stampLabel, epicFingerprint, syncStatus, isPending } from '${path.resolve('src/core/model.ts')}';
export { serializeBacklog, deserializeBacklog, BacklogStore, backlogPath } from '${path.resolve('src/core/store.ts')}';
export { loadQuality, saveQuality, deleteQuality, qualityPath } from '${path.resolve('src/core/rubric/store.ts')}';
export { evaluateBacklog, scoreCriteria, fixInstruction, cacheKey, overrideKey } from '${path.resolve('src/core/rubric/score.ts')}';
export { DEFAULT_RUBRIC } from '${path.resolve('src/core/rubric/types.ts')}';
export { RULE_IDS } from '${path.resolve('src/core/rubric/rules.ts')}';
export { qualityLabels, qualityNote, staleQualityLabels, qualityLabelVocabulary } from '${path.resolve('src/core/rubric/labels.ts')}';
export { parseEpicMarkdown, parseStoryMarkdown } from '${path.resolve('src/core/pipeline/parseIssue.ts')}';
export { storyToMarkdown } from '${path.resolve('src/core/model.ts')}';
export { STORY_CRITERIA, EPIC_CRITERIA } from '${path.resolve('src/core/rubric/criteria.ts')}';
`
);

// CJS, matching how the extension itself is bundled: some deps (yaml) are CJS
// and cannot be dynamically required from an ESM bundle.
const out = path.join(dir, 'bundle.cjs');
await esbuild.build({
  entryPoints: [entry],
  bundle: true,
  outfile: out,
  platform: 'node',
  format: 'cjs',
  logLevel: 'error'
});

const m = createRequire(import.meta.url)(out);

let pass = 0;
let fail = 0;
const check = (name, cond, detail = '') => {
  if (cond) {
    pass++;
    console.log(`  ok    ${name}`);
  } else {
    fail++;
    console.log(`  FAIL  ${name}${detail ? `\n        ${detail}` : ''}`);
  }
};

/* ------------------------------------------------ confluence storage format */

const storage = `
<h1>Payments Revamp</h1>
<p>We need to <strong>reduce</strong> checkout friction.</p>
<ac:structured-macro ac:name="info"><ac:rich-text-body><p>Deadline is Q3.</p></ac:rich-text-body></ac:structured-macro>
<h2>Requirements</h2>
<ul><li>Support Apple Pay</li><li>Support saved cards</li></ul>
<table><tbody>
<tr><th>Field</th><th>Rule</th></tr>
<tr><td>Amount</td><td>Must be positive</td></tr>
</tbody></table>
<ac:structured-macro ac:name="code"><ac:plain-text-body><![CDATA[POST /v1/charge]]></ac:plain-text-body></ac:structured-macro>
<ac:task-list><ac:task><ac:task-id>1</ac:task-id><ac:status>complete</ac:status><ac:task-body>Legal review</ac:task-body></ac:task></ac:task-list>
`;

const md = m.storageToMarkdown(storage);
check('storage: heading survives', md.includes('# Payments Revamp'), md.slice(0, 200));
check('storage: bold survives', md.includes('**reduce**'));
check('storage: info macro body survives', md.includes('Deadline is Q3'));
check('storage: list survives', md.includes('- Support Apple Pay'));
check('storage: table becomes a markdown table', md.includes('| Field | Rule |'), md);
check('storage: code macro survives', md.includes('POST /v1/charge'));
check('storage: task body survives', md.includes('Legal review'));
check('storage: no raw ac: tags leak through', !md.includes('<ac:'), md);

/* --------------------------------------------------------- markdown <-> ADF */

const source = [
  '*Outcome:* Faster checkout',
  '',
  '## In scope',
  '- Apple Pay',
  '- Saved cards',
  '',
  '## Acceptance criteria',
  '- **Given** a saved card **when** the user checks out **then** no re-entry is required',
  '',
  '```ts',
  'const x = 1;',
  '```',
  '',
  'See [the spec](https://example.com/spec).',
  '',
  '---',
  '_Generated by ReqForge._'
].join('\n');

const adf = m.markdownToAdf(source);
check('adf: is a doc', adf.type === 'doc' && adf.version === 1);
check('adf: has heading nodes', adf.content.some((n) => n.type === 'heading'));
check('adf: has bullet list', adf.content.some((n) => n.type === 'bulletList'));
check('adf: has code block', adf.content.some((n) => n.type === 'codeBlock'));
check('adf: has rule', adf.content.some((n) => n.type === 'rule'));

const codeBlock = adf.content.find((n) => n.type === 'codeBlock');
check('adf: code block keeps language', codeBlock?.attrs?.language === 'ts', JSON.stringify(codeBlock));
check('adf: code block keeps content', codeBlock?.content?.[0]?.text === 'const x = 1;');

const flat = JSON.stringify(adf);
check('adf: link mark emitted', flat.includes('"type":"link"') && flat.includes('https://example.com/spec'));
check('adf: strong mark emitted', flat.includes('"type":"strong"'));
check('adf: no empty text nodes', !flat.includes('"text":""'), 'empty text nodes are rejected by Jira');

const roundTrip = m.adfToMarkdown(adf);
check('adf round trip: keeps heading', roundTrip.includes('## In scope'));
check('adf round trip: keeps list item', roundTrip.includes('- Apple Pay'));
check('adf round trip: keeps link', roundTrip.includes('[the spec](https://example.com/spec)'));

check('adf: empty input still produces a valid doc', m.markdownToAdf('').content.length > 0);

/* ------------------------------------------------------------ page id parse */

check('pageId: bare id', m.extractPageId('123456') === '123456');
check(
  'pageId: modern url',
  m.extractPageId('https://acme.atlassian.net/wiki/spaces/PROD/pages/98765/My+PRD') === '98765'
);
check('pageId: legacy url', m.extractPageId('https://acme.atlassian.net/wiki/pages/viewpage.action?pageId=555') === '555');
let threw = false;
try {
  m.extractPageId('not-a-page');
} catch {
  threw = true;
}
check('pageId: rejects nonsense with a clear error', threw);

/* ------------------------------------------------------- model + serialization */

const epic = {
  ref: 'apple-pay',
  title: 'Apple Pay at checkout',
  outcome: 'Shoppers can pay without typing card details',
  description: 'Body text.',
  inScope: ['iOS Safari'],
  outOfScope: ['Android'],
  acceptanceCriteria: [{ given: 'a device with Apple Pay', when: 'the user checks out', then: 'the sheet appears' }],
  dependsOn: [],
  sizing: 'M',
  openQuestions: ['Which PSP?'],
  sourceEvidence: ['reduce checkout friction']
};

const epicMd = m.epicToMarkdown(epic);
check('epic markdown: has outcome', epicMd.includes('Faster'.length ? 'Outcome:' : ''));
check('epic markdown: has AC section', epicMd.includes('## Acceptance criteria'));
check('epic markdown: has out of scope', epicMd.includes('## Out of scope'));
check('epic markdown: converts cleanly to ADF', m.markdownToAdf(epicMd).content.length > 5);

check('stamp label is JQL-safe', /^[A-Za-z0-9_-]+$/.test(m.stampLabel('12345', 'apple-pay')));
check('stamp label is stable', m.stampLabel('12345', 'apple-pay') === m.stampLabel('12345', 'apple-pay'));
check(
  'fingerprint changes when content changes',
  m.epicFingerprint(epic) !== m.epicFingerprint({ ...epic, title: 'Different' })
);
check('fingerprint is stable across identical objects', m.epicFingerprint(epic) === m.epicFingerprint({ ...epic }));

const backlog = {
  version: 1,
  source: { kind: 'confluence', pageId: '1', title: 'T', url: 'u', ingestedAt: 'now' },
  target: { projectKey: 'ACME', epicIssueType: 'Epic', storyIssueType: 'Story' },
  prd: { title: 'T', summary: 's', goals: [], nonGoals: [], personas: [], constraints: [], openQuestions: [], risks: [] },
  epics: [{ ...epic, sync: {}, stories: [] }]
};

const yaml = m.serializeBacklog(backlog);
const back = m.deserializeBacklog(yaml);
check('backlog round trips through yaml', back.epics[0].ref === 'apple-pay' && back.target.projectKey === 'ACME');
check('backlog yaml carries the editing header', yaml.startsWith('# ReqForge backlog'));

let versionRejected = false;
try {
  m.deserializeBacklog('version: 99\n');
} catch {
  versionRejected = true;
}
check('backlog rejects an unknown schema version', versionRejected);

/* ------------------------------------------- hand-edited files must survive */

// Regression: a hand-edited backlog that omits optional lists used to load as
// undefined and then throw "Cannot read properties of undefined (reading
// 'length')" from inside epicToMarkdown, at push time.
const handEdited = `
version: 1
source: {kind: confluence, pageId: "1", title: T, url: u, ingestedAt: now}
target: {projectKey: ACME}
prd: {title: T, summary: s}
epics:
  - ref: minimal
    title: An epic with every optional field removed
    outcome: Something useful happens
    description: Body.
    stories:
      - ref: minimal-story
        epicRef: minimal
        title: A story with no optional fields
        narrative: {asA: user, iWant: a thing, soThat: a benefit}
        acceptanceCriteria:
          - {given: g, when: w, then: t}
`;

let loaded;
try {
  loaded = m.deserializeBacklog(handEdited);
  check('hand-edited backlog loads', true);
} catch (err) {
  check('hand-edited backlog loads', false, err.message);
}

if (loaded) {
  const e = loaded.epics[0];
  check('missing lists default to []', Array.isArray(e.inScope) && Array.isArray(e.acceptanceCriteria));
  check('missing sync defaults to {}', e.sync && typeof e.sync === 'object' && !e.sync.jiraKey);
  check('missing issue types default', loaded.target.epicIssueType === 'Epic' && loaded.target.storyIssueType === 'Story');
  check('missing prd lists default to []', Array.isArray(loaded.prd.goals) && Array.isArray(loaded.prd.openQuestions));
  try {
    const rendered = m.epicToMarkdown(e);
    check('minimal epic renders without throwing', rendered.includes('Something useful happens'));
    check('minimal epic renders to valid ADF', m.markdownToAdf(rendered).content.length > 0);
  } catch (err) {
    check('minimal epic renders without throwing', false, err.message);
  }
}

// A genuinely broken file must say which field is wrong, not throw a TypeError.
let msg = '';
try {
  m.deserializeBacklog('version: 1\nsource: {kind: confluence, pageId: "1", title: T, url: u, ingestedAt: n}\ntarget: {projectKey: A}\nprd: {title: T, summary: s}\nepics: [{ref: "Bad Ref!", title: x, outcome: y, description: z}]\n');
} catch (err) {
  msg = err.message;
}
check('invalid field is reported with its path', msg.includes('epics.0.ref'), msg);

/* ------------------------------------------------------------------ rubric */

const goodStory = {
  ref: 'good-story',
  epicRef: 'good',
  title: 'Show saved cards at checkout',
  narrative: {
    asA: 'returning shopper',
    iWant: 'to see the cards I have saved',
    soThat: 'I can complete payment without finding my wallet'
  },
  description: '',
  acceptanceCriteria: [{ given: 'a shopper with two saved cards', when: 'the checkout page loads', then: 'both cards are listed' }],
  points: 3,
  openQuestions: [],
  sync: {}
};

const goodEpic = {
  ref: 'good',
  title: 'Saved cards at checkout',
  outcome: 'Returning shoppers pay without re-entering card details',
  description: 'Body.',
  inScope: ['iOS Safari'],
  outOfScope: ['Android'],
  acceptanceCriteria: [{ given: 'a saved card', when: 'the shopper checks out', then: 'no re-entry is required' }],
  dependsOn: [],
  sizing: 'M',
  openQuestions: [],
  sourceEvidence: ['reduce checkout friction'],
  sync: {},
  stories: [goodStory]
};

const backlogOf = (epics) => ({
  version: 1,
  source: { kind: 'confluence', pageId: '1', title: 'T', url: 'u', ingestedAt: 'now' },
  target: { projectKey: 'ACME', epicIssueType: 'Epic', storyIssueType: 'Story' },
  prd: { title: 'T', summary: 's', goals: [], nonGoals: [], personas: [], constraints: [], openQuestions: [], risks: [] },
  epics
});

const findingsFor = (backlog, ref) => {
  const q = m.evaluateBacklog(backlog, m.DEFAULT_RUBRIC);
  const item = q.items.find((i) => i.ref === ref);
  return [...item.blockedBy, ...item.warnings].map((f) => f.ruleId);
};

check('rubric: a clean epic produces no blockers or warnings', (() => {
  const ids = findingsFor(backlogOf([goodEpic]), 'good');
  return ids.length === 0;
})(), JSON.stringify(findingsFor(backlogOf([goodEpic]), 'good')));

check('rubric: a clean story produces no blockers or warnings',
  findingsFor(backlogOf([goodEpic]), 'good-story').length === 0,
  JSON.stringify(findingsFor(backlogOf([goodEpic]), 'good-story')));

// Each of these must fire, or the rule is dead code.
const epicCases = [
  ['has-outcome', { ...goodEpic, outcome: '  ' }],
  ['has-acceptance-criteria', { ...goodEpic, acceptanceCriteria: [] }],
  ['complete-acceptance-criteria', { ...goodEpic, acceptanceCriteria: [{ given: 'x', when: '', then: 'y' }] }],
  ['dependencies-resolve', { ...goodEpic, dependsOn: ['nope'] }],
  ['no-self-dependency', { ...goodEpic, dependsOn: ['good'] }],
  ['has-evidence', { ...goodEpic, sourceEvidence: [] }],
  ['has-out-of-scope', { ...goodEpic, outOfScope: [] }],
  ['sizing-xl', { ...goodEpic, sizing: 'XL' }],
  ['no-stories', { ...goodEpic, stories: [] }],
  ['layer-shaped', { ...goodEpic, title: 'The payments API' }],
  ['vague-acceptance-criteria', { ...goodEpic, acceptanceCriteria: [{ given: 'a card', when: 'it is used', then: 'it works properly' }] }],
  ['too-many-stories', { ...goodEpic, stories: Array.from({ length: 13 }, (_, i) => ({ ...goodStory, ref: `s${i}` })) }]
];

for (const [ruleId, epic] of epicCases) {
  const ids = findingsFor(backlogOf([epic]), 'good');
  check(`rubric rule fires: ${ruleId}`, ids.includes(ruleId), `got: ${ids.join(', ') || '(none)'}`);
}

const storyCases = [
  ['has-narrative', { ...goodStory, narrative: { ...goodStory.narrative, soThat: '' } }],
  ['has-acceptance-criteria', { ...goodStory, acceptanceCriteria: [] }],
  ['generic-persona', { ...goodStory, narrative: { ...goodStory.narrative, asA: 'user' } }],
  ['too-large', { ...goodStory, points: 13 }],
  ['vague-acceptance-criteria', { ...goodStory, acceptanceCriteria: [{ given: 'a', when: 'b', then: 'it is user-friendly' }] }],
  ['benefit-restates-want', { ...goodStory, narrative: { asA: 'shopper', iWant: 'to see saved cards listed', soThat: 'saved cards are listed' } }]
];

for (const [ruleId, story] of storyCases) {
  const ids = findingsFor(backlogOf([{ ...goodEpic, stories: [story] }]), 'good-story');
  check(`rubric rule fires: ${ruleId} (story)`, ids.includes(ruleId), `got: ${ids.join(', ') || '(none)'}`);
}

/* scoring and gating */

const allThrees = m.STORY_CRITERIA.map((c) => ({ id: c.id, rating: 3, justification: 'x', suggestion: '' }));
const allZeros = m.STORY_CRITERIA.map((c) => ({ id: c.id, rating: 0, justification: 'x', suggestion: '' }));

check('score: all 3s is 100', m.scoreCriteria('story', allThrees, m.DEFAULT_RUBRIC) === 100);
check('score: all 0s is 0', m.scoreCriteria('story', allZeros, m.DEFAULT_RUBRIC) === 0);
check(
  'score: disabling a criterion does not cap the maximum',
  m.scoreCriteria('story', allThrees.filter((c) => c.id !== 'invest-testable'), {
    ...m.DEFAULT_RUBRIC,
    weights: { 'invest-testable': 0 }
  }) === 100
);
check(
  'score: unassessed criteria are excluded, not counted as zero',
  m.scoreCriteria('story', allThrees.slice(0, 2), m.DEFAULT_RUBRIC) === 100
);
check(
  'score: weighting Testable higher lowers the score when only Testable is poor',
  m.scoreCriteria('story', m.STORY_CRITERIA.map((c) => ({ id: c.id, rating: c.id === 'invest-testable' ? 0 : 3, justification: 'x', suggestion: '' })), m.DEFAULT_RUBRIC) < 80
);

// The gate: a blocker must fail an item no matter how well it scores.
const blocked = backlogOf([{ ...goodEpic, acceptanceCriteria: [] }]);
const cached = new Map([[m.cacheKey('epic', 'good', m.epicFingerprint({ ...goodEpic, acceptanceCriteria: [] })), m.EPIC_CRITERIA.map((c) => ({ id: c.id, rating: 3, justification: 'x', suggestion: '' }))]]);
const blockedQ = m.evaluateBacklog(blocked, m.DEFAULT_RUBRIC, cached);
const blockedItem = blockedQ.items.find((i) => i.ref === 'good');
check('gate: a perfect score still fails when a blocker fired', blockedItem.score === 100 && blockedItem.passed === false);

const cleanCached = new Map([[m.cacheKey('epic', 'good', m.epicFingerprint(goodEpic)), m.EPIC_CRITERIA.map((c) => ({ id: c.id, rating: 3, justification: 'x', suggestion: '' }))]]);
const cleanItem = m.evaluateBacklog(backlogOf([goodEpic]), m.DEFAULT_RUBRIC, cleanCached).items.find((i) => i.ref === 'good');
check('gate: a clean item at 100 passes', cleanItem.passed === true);

const lowCached = new Map([[m.cacheKey('epic', 'good', m.epicFingerprint(goodEpic)), m.EPIC_CRITERIA.map((c) => ({ id: c.id, rating: 1, justification: 'x', suggestion: '' }))]]);
const lowItem = m.evaluateBacklog(backlogOf([goodEpic]), m.DEFAULT_RUBRIC, lowCached).items.find((i) => i.ref === 'good');
check('gate: below threshold fails', lowItem.score < 70 && lowItem.passed === false);

// With requireReview on, an item nobody has reviewed must not read as passing.
check('gate: with requireReview, an unassessed item is not treated as passing',
  cleanItem.deterministicOnly === false &&
  m.evaluateBacklog(backlogOf([goodEpic]), { ...m.DEFAULT_RUBRIC, requireReview: true })
    .items.find((i) => i.ref === 'good').passed === false);

// Editing an item must invalidate its cached assessment.
const edited = { ...goodEpic, title: 'A different title' };
const staleItem = m.evaluateBacklog(backlogOf([edited]), m.DEFAULT_RUBRIC, cleanCached).items.find((i) => i.ref === 'good');
check('cache: editing an item invalidates its assessment', staleItem.deterministicOnly === true);

check('fix instruction names the actual problems',
  m.fixInstruction(blockedItem).includes('No acceptance criteria'),
  m.fixInstruction(blockedItem));

/* --------------------------------------------------- overrides and waivers */

const noAc = { ...goodEpic, acceptanceCriteria: [] };
const noAcBacklog = backlogOf([noAc]);
const noAcPrint = m.epicFingerprint(noAc);
const perfectEpic = m.EPIC_CRITERIA.map((c) => ({ id: c.id, rating: 3, justification: 'x', suggestion: '' }));
const poorEpic = m.EPIC_CRITERIA.map((c) => ({ id: c.id, rating: 1, justification: 'x', suggestion: '' }));

// Waiving a blocker clears it from the verdict but keeps it visible.
const waiver = new Map([
  [m.overrideKey('epic', 'good'), { level: 'epic', ref: 'good', waivedRules: ['has-acceptance-criteria'], reasons: { 'has-acceptance-criteria': 'covered by the linked test plan' } }]
]);
const waivedItem = m.evaluateBacklog(noAcBacklog, m.DEFAULT_RUBRIC, new Map([[m.cacheKey('epic', 'good', noAcPrint), perfectEpic]]), waiver).items.find((i) => i.ref === 'good');
check('waiver: a waived blocker no longer blocks', waivedItem.blockedBy.length === 0 && waivedItem.passed === true);
check('waiver: the waived finding stays visible with its reason',
  waivedItem.waived.length === 1 && waivedItem.waived[0].reason.includes('test plan'));

// Without the waiver the same item must still fail.
const unwaivedItem = m.evaluateBacklog(noAcBacklog, m.DEFAULT_RUBRIC, new Map([[m.cacheKey('epic', 'good', noAcPrint), perfectEpic]])).items.find((i) => i.ref === 'good');
check('waiver: removing it restores the blocker', unwaivedItem.blockedBy.length === 1 && unwaivedItem.passed === false);

// Accepting below threshold passes the item but records why.
const accept = new Map([
  [m.overrideKey('epic', 'good'), { level: 'epic', ref: 'good', waivedRules: [], reasons: {}, acceptedBelowThreshold: { reason: 'spike, detail follows', at: 'now' } }]
]);
const acceptedItem = m.evaluateBacklog(backlogOf([goodEpic]), m.DEFAULT_RUBRIC, new Map([[m.cacheKey('epic', 'good', m.epicFingerprint(goodEpic)), poorEpic]]), accept).items.find((i) => i.ref === 'good');
check('accept: a low score passes once accepted', acceptedItem.score === 33 && acceptedItem.passed === true);
check('accept: the reason is retained', acceptedItem.acceptedBelowThreshold.reason.includes('spike'));

// Acceptance must NOT buy off a blocker — that would make the gate meaningless.
const acceptWithBlocker = m.evaluateBacklog(noAcBacklog, m.DEFAULT_RUBRIC, new Map([[m.cacheKey('epic', 'good', noAcPrint), perfectEpic]]), accept).items.find((i) => i.ref === 'good');
check('accept: cannot override a blocker', acceptWithBlocker.blockedBy.length === 1 && acceptWithBlocker.passed === false);

// requireReview controls whether unreviewed items block.
const strict = m.evaluateBacklog(backlogOf([goodEpic]), { ...m.DEFAULT_RUBRIC, requireReview: true }).items.find((i) => i.ref === 'good');
const relaxed = m.evaluateBacklog(backlogOf([goodEpic]), { ...m.DEFAULT_RUBRIC, requireReview: false }).items.find((i) => i.ref === 'good');
check('requireReview true: an unreviewed item fails', strict.passed === false && strict.deterministicOnly === true);
check('requireReview false: an unreviewed clean item passes', relaxed.passed === true && relaxed.deterministicOnly === true);
check('requireReview false: an unreviewed item with a blocker still fails',
  m.evaluateBacklog(noAcBacklog, { ...m.DEFAULT_RUBRIC, requireReview: false }).items.find((i) => i.ref === 'good').passed === false);

/* ------------------------------------------------------- labels and notes */

const mk = (over) => ({ level: 'story', ref: 'r', title: 't', score: 60, threshold: 70, passed: false,
  blockedBy: [], warnings: [], criteria: [], assessedHash: 'h', assessedAt: 'now', deterministicOnly: false, waived: [], ...over });

const weak = m.STORY_CRITERIA.map((c, i) => ({ id: c.id, rating: i < 2 ? 0 : 3, justification: 'x', suggestion: 'y' }));
const below = mk({ score: 55, criteria: weak });
const okItem = mk({ score: 90, passed: true, criteria: m.STORY_CRITERIA.map((c) => ({ id: c.id, rating: 3, justification: 'x', suggestion: '' })) });
const unreviewed = mk({ score: 0, deterministicOnly: true, criteria: [] });

const belowLabels = m.qualityLabels(below);
check('labels: below threshold is tagged', belowLabels.includes('reqforge-quality-below-threshold'), belowLabels.join(','));
check('labels: the weakest criteria are named', belowLabels.some((l) => l.startsWith('reqforge-needs-')), belowLabels.join(','));
check('labels: criterion labels are capped at 3', belowLabels.filter((l) => l.startsWith('reqforge-needs-')).length <= 3);
check('labels: a passing item is tagged ok', m.qualityLabels(okItem).includes('reqforge-quality-ok'));
check('labels: an unreviewed item is tagged not-reviewed',
  m.qualityLabels(unreviewed).join(',') === 'reqforge-not-reviewed');
check('labels: every label is valid for Jira (no whitespace)',
  [...m.qualityLabelVocabulary(), ...belowLabels].every((l) => /^[a-z0-9-]+$/.test(l)));
check('labels: stale set excludes the current ones',
  m.staleQualityLabels(below).every((l) => !belowLabels.includes(l)) &&
  m.staleQualityLabels(below).includes('reqforge-quality-ok'));

const note = m.qualityNote(below);
check('note: states the score and threshold', note.includes('55/100') && note.includes('70'), note);
check('note: names the weakest criteria', /Weakest:/.test(note), note);
check('note: a passing item gets a one-liner', m.qualityNote(okItem).includes('90/100'));
check('note: an unreviewed item says so', m.qualityNote(unreviewed).includes('not reviewed'));
check('note: renders to valid ADF', m.markdownToAdf(note).content.length > 0);

const accepted = mk({ score: 40, passed: true, acceptedBelowThreshold: { reason: 'spike', at: 'now' }, criteria: weak });
check('labels: an accepted item is tagged accepted', m.qualityLabels(accepted).includes('reqforge-quality-accepted'));
check('note: an accepted item records the reason', m.qualityNote(accepted).includes('spike'));

/* enforcement defaults */
check('default enforcement is label, not block', m.DEFAULT_RUBRIC.enforcement === 'label');
check('default does not require a review to push', m.DEFAULT_RUBRIC.requireReview === false);
check('an unreviewed clean item passes under the defaults',
  m.evaluateBacklog(backlogOf([goodEpic]), m.DEFAULT_RUBRIC).items.find((i) => i.ref === 'good').passed === true);
check('a structurally broken item still fails under the defaults',
  m.evaluateBacklog(backlogOf([{ ...goodEpic, acceptanceCriteria: [] }]), m.DEFAULT_RUBRIC).items.find((i) => i.ref === 'good').blockedBy.length === 1);

check('rubric exposes every rule id for config', m.RULE_IDS.length >= 18 && m.RULE_IDS.includes('generic-persona'));
check('INVEST is complete and correctly named',
  ['Independent','Negotiable','Valuable','Estimable','Small','Testable'].every((n) => m.STORY_CRITERIA.some((c) => c.name === n)));

/* ----------------------------------------- reading an issue back into shape */

{
  // The round trip is the contract: anything we render into a Jira description
  // must come back as the same structure, or "edit an existing epic" silently
  // loses fields the moment somebody saves.
  const rendered = m.epicToMarkdown(goodEpic);
  const back = m.parseEpicMarkdown('KAN-95', goodEpic.title, rendered);

  check('round trip epic: title', back.title === goodEpic.title);
  check('round trip epic: outcome', back.outcome === goodEpic.outcome, back.outcome);
  check('round trip epic: description', back.description === goodEpic.description, back.description);
  check('round trip epic: in scope', back.inScope.join('|') === goodEpic.inScope.join('|'), back.inScope.join('|'));
  check('round trip epic: out of scope', back.outOfScope.join('|') === goodEpic.outOfScope.join('|'));
  check('round trip epic: acceptance criteria',
    JSON.stringify(back.acceptanceCriteria) === JSON.stringify(goodEpic.acceptanceCriteria),
    JSON.stringify(back.acceptanceCriteria));
  check('round trip epic: sizing', back.sizing === goodEpic.sizing);
  check('round trip epic: ref comes from the issue key', back.ref === 'kan-95');

  const richEpic = { ...goodEpic, openQuestions: ['Who owns it?'], dependsOn: ['other-epic'], sizing: 'XL' };
  const richBack = m.parseEpicMarkdown('KAN-1', richEpic.title, m.epicToMarkdown(richEpic));
  check('round trip epic: open questions', richBack.openQuestions.join('|') === 'Who owns it?');
  check('round trip epic: dependsOn', richBack.dependsOn.join('|') === 'other-epic');
  check('round trip epic: XL sizing survives', richBack.sizing === 'XL');

  const st = m.parseStoryMarkdown('KAN-96', goodStory.title, m.storyToMarkdown(goodStory), 'kan-95');
  check('round trip story: narrative asA', st.narrative.asA === goodStory.narrative.asA, st.narrative.asA);
  check('round trip story: narrative iWant', st.narrative.iWant === goodStory.narrative.iWant);
  check('round trip story: narrative soThat', st.narrative.soThat === goodStory.narrative.soThat);
  check('round trip story: acceptance criteria',
    JSON.stringify(st.acceptanceCriteria) === JSON.stringify(goodStory.acceptanceCriteria));
  check('round trip story: points', st.points === goodStory.points);
  check('round trip story: parent ref', st.epicRef === 'kan-95');

  // A quality note we appended on a previous push must not leak into the body.
  const withNote = m.epicToMarkdown(goodEpic) + '\n\n_Quality: 55/100, below the threshold of 70._';
  const noNote = m.parseEpicMarkdown('KAN-95', goodEpic.title, withNote);
  check('round trip: a previously appended quality note is stripped',
    !noNote.description.includes('Quality:') && !JSON.stringify(noNote).includes('55/100'));

  // An issue nobody generated: no structure, but it must still load.
  const handWritten = m.parseEpicMarkdown('KAN-7', 'Some epic', 'We need to sort out the payments thing.\nTalk to Dave.');
  check('hand-written issue: body lands in description', handWritten.description.includes('payments thing'));
  check('hand-written issue: no invented outcome', handWritten.outcome === '');
  check('hand-written issue: no invented criteria', handWritten.acceptanceCriteria.length === 0);

  const handStory = m.parseStoryMarkdown('KAN-8', 'A story', 'Just some prose.', 'kan-7');
  check('hand-written story: gets a placeholder criterion so it can load', handStory.acceptanceCriteria.length === 1);
  check('hand-written story: defaults to 3 points', handStory.points === 3);

  // Non-Gherkin bullets under Acceptance criteria are somebody's work — keep them.
  const loose = m.parseEpicMarkdown('KAN-9', 'x', '## Acceptance criteria\n- It must be fast\n- It must log');
  check('loose criteria are kept rather than dropped', loose.acceptanceCriteria.length === 2 &&
    loose.acceptanceCriteria[0].then === 'It must be fast');
}

/* ------------------------------- the round trip that actually happens in Jira */

{
  // The earlier round-trip tests parse the markdown we rendered. Real data goes
  // markdown -> ADF -> Jira -> ADF -> markdown, and that is where a story's
  // three-line narrative was being collapsed into one line, leaving iWant and
  // soThat empty and the backlog file unloadable.
  const viaJira = (md) => m.adfToMarkdown(m.markdownToAdf(md));

  const st = m.parseStoryMarkdown('K-1', goodStory.title, viaJira(m.storyToMarkdown(goodStory)), 'e');
  check('via ADF: narrative asA survives', st.narrative.asA === goodStory.narrative.asA, st.narrative.asA);
  check('via ADF: narrative iWant survives', st.narrative.iWant === goodStory.narrative.iWant, st.narrative.iWant);
  check('via ADF: narrative soThat survives', st.narrative.soThat === goodStory.narrative.soThat, st.narrative.soThat);
  check('via ADF: acceptance criteria survive',
    JSON.stringify(st.acceptanceCriteria) === JSON.stringify(goodStory.acceptanceCriteria));
  check('via ADF: points survive', st.points === goodStory.points);

  const ep = m.parseEpicMarkdown('K-2', goodEpic.title, viaJira(m.epicToMarkdown(goodEpic)));
  check('via ADF: epic outcome survives', ep.outcome === goodEpic.outcome, ep.outcome);
  check('via ADF: epic in scope survives', ep.inScope.join('|') === goodEpic.inScope.join('|'));
  check('via ADF: epic criteria survive',
    JSON.stringify(ep.acceptanceCriteria) === JSON.stringify(goodEpic.acceptanceCriteria));

  // Even if a renderer somewhere does collapse it, the parser must cope.
  const collapsed = m.parseStoryMarkdown('K-3', 'T',
    '**As a** shopper **I want** to pay **So that** I am done\n\n## Acceptance criteria\n- **Given** a **when** b **then** c', 'e');
  check('collapsed narrative: asA does not swallow the rest', collapsed.narrative.asA === 'shopper', collapsed.narrative.asA);
  check('collapsed narrative: iWant is recovered', collapsed.narrative.iWant === 'to pay');
  check('collapsed narrative: soThat is recovered', collapsed.narrative.soThat === 'I am done');

  // A story with no narrative at all must still load; the rubric flags it.
  const empty = m.deserializeBacklog(m.serializeBacklog(backlogOf([{ ...goodEpic,
    stories: [{ ...goodStory, narrative: { asA: '', iWant: '', soThat: '' } }] }])));
  check('a story with no narrative still loads', empty.epics[0].stories.length === 1);
  const q = m.evaluateBacklog(empty, m.DEFAULT_RUBRIC).items.find((i) => i.ref === goodStory.ref);
  check('a story with no narrative is blocked by the rubric instead',
    q.blockedBy.some((b) => b.ruleId === 'has-narrative'), JSON.stringify(q.blockedBy));
}

/* -------------------------------- a slice of a backlog is not a broken one */

{
  const dependent = { ...goodEpic, dependsOn: ['something-elsewhere'] };

  // A complete decomposition: a dependency on an epic that is not there is broken.
  const whole = backlogOf([dependent]);
  const wholeQ = m.evaluateBacklog(whole, m.DEFAULT_RUBRIC).items.find((i) => i.ref === 'good');
  check('complete backlog: a dangling dependency blocks',
    wholeQ.blockedBy.some((f) => f.ruleId === 'dependencies-resolve'),
    JSON.stringify(wholeQ.blockedBy.map((f) => f.ruleId)));

  // One epic pulled out of Jira: the same dependency points outside the slice,
  // which is ordinary, and blocking on it makes the import unusable.
  const slice = backlogOf([dependent]);
  slice.source.kind = 'jira';
  const sliceQ = m.evaluateBacklog(slice, m.DEFAULT_RUBRIC).items.find((i) => i.ref === 'good');
  check('imported epic: an external dependency does not block',
    !sliceQ.blockedBy.some((f) => f.ruleId === 'dependencies-resolve'),
    JSON.stringify(sliceQ.blockedBy.map((f) => f.ruleId)));
  check('imported epic: it is still reported, as information',
    sliceQ.warnings.some((f) => f.ruleId === 'external-dependency' && f.message.includes('something-elsewhere')),
    JSON.stringify(sliceQ.warnings.map((f) => f.ruleId)));
  check('imported epic: a resolvable dependency reports nothing',
    m.evaluateBacklog(
      (() => { const b = backlogOf([{ ...goodEpic, dependsOn: [] }]); b.source.kind = 'jira'; return b; })(),
      m.DEFAULT_RUBRIC
    ).items.find((i) => i.ref === 'good').warnings.every((f) => f.ruleId !== 'external-dependency'));

  // Same family: traceability is to a source document an import does not have.
  const noEvidence = backlogOf([{ ...goodEpic, sourceEvidence: [] }]);
  check('complete backlog: missing evidence warns',
    m.evaluateBacklog(noEvidence, m.DEFAULT_RUBRIC).items.find((i) => i.ref === 'good')
      .warnings.some((f) => f.ruleId === 'has-evidence'));
  const importedNoEvidence = backlogOf([{ ...goodEpic, sourceEvidence: [] }]);
  importedNoEvidence.source.kind = 'jira';
  check('imported epic: missing evidence does not warn',
    m.evaluateBacklog(importedNoEvidence, m.DEFAULT_RUBRIC).items.find((i) => i.ref === 'good')
      .warnings.every((f) => f.ruleId !== 'has-evidence'));

  // Depending on yourself is broken either way.
  const selfDep = backlogOf([{ ...goodEpic, dependsOn: ['good'] }]);
  selfDep.source.kind = 'jira';
  check('imported epic: a self-dependency still blocks',
    m.evaluateBacklog(selfDep, m.DEFAULT_RUBRIC).items.find((i) => i.ref === 'good')
      .blockedBy.some((f) => f.ruleId === 'no-self-dependency'));
}

/* ------------------------------------------------------------ sync status */

{
  const hash = m.epicFingerprint(goodEpic);
  const other = m.epicFingerprint({ ...goodEpic, title: 'Changed' });

  check('sync: no key means new', m.syncStatus({}, hash) === 'new');
  check('sync: key with a matching hash means synced', m.syncStatus({ jiraKey: 'A-1', pushedHash: hash }, hash) === 'synced');
  // The regression: a present pushedHash used to be taken as proof of being up
  // to date, so anything edited after a push showed as synced and was not sent.
  check('sync: key with a stale hash means edited',
    m.syncStatus({ jiraKey: 'A-1', pushedHash: other }, hash) === 'edited');
  check('sync: an adopted issue never pushed from here counts as edited',
    m.syncStatus({ jiraKey: 'A-1' }, hash) === 'edited');

  check('pending: a synced item is not pending', m.isPending({ jiraKey: 'A-1', pushedHash: hash }, hash) === false);
  check('pending: an edited item is pending', m.isPending({ jiraKey: 'A-1', pushedHash: other }, hash) === true);
  check('pending: a new item is pending', m.isPending({}, hash) === true);
}

/* ------------------------------------------------------- backlog store CRUD */

const memFs = () => {
  const files = new Map();
  return {
    files,
    async read(p) { return files.get(p); },
    async write(p, c) { files.set(p, c); },
    async list(dir) { return [...files.keys()].filter((k) => k.startsWith(dir + '/')).map((k) => k.slice(dir.length + 1)); },
    async remove(p) { files.delete(p); }
  };
};

{
  const fs = memFs();
  const store = new m.BacklogStore(fs, '.reqforge');
  const b = backlogOf([goodEpic]);
  b.source.title = 'Payments';

  await store.save('payments', b);
  await store.save('other', b);
  await m.saveQuality(fs, '.reqforge', 'payments', { assessments: new Map([['k', []]]), overrides: new Map() });

  check('store: saved backlogs are listed', (await store.listSlugs()).sort().join(',') === 'other,payments');
  check('store: a saved backlog loads back', (await store.load('payments'))?.source.title === 'Payments');
  check('store: the quality sidecar is written', fs.files.has(m.qualityPath('.reqforge', 'payments')));

  await store.remove('payments');
  await m.deleteQuality(fs, '.reqforge', 'payments');

  check('delete: the backlog is gone from the list', (await store.listSlugs()).join(',') === 'other');
  check('delete: loading it returns nothing', (await store.load('payments')) === undefined);
  check('delete: its quality sidecar is gone too', !fs.files.has(m.qualityPath('.reqforge', 'payments')));
  check('delete: other backlogs are untouched', (await store.load('other'))?.source.title === 'Payments');
  check('delete: deleting a missing backlog is not an error', await store.remove('nope').then(() => true).catch(() => false));
}

/* Regression: a save must leave the previous contents recoverable. This file is
   the only record of work that has not reached Jira. */
{
  const fs = memFs();
  const store = new m.BacklogStore(fs, '.reqforge');
  const one = backlogOf([goodEpic]);
  const emptied = backlogOf([]);

  await store.save('x', one);
  check('backup: the first save creates no backup', !fs.files.has('.reqforge/x.backlog.yaml.bak'));

  await store.save('x', emptied);
  const bak = fs.files.get('.reqforge/x.backlog.yaml.bak');
  check('backup: the previous contents are kept', Boolean(bak) && bak.includes('good'));
  check('backup: the current file has the new contents', (await store.load('x')).epics.length === 0);
  check('backup: the backup still parses as a backlog', m.deserializeBacklog(bak).epics.length === 1);
  check('backup: backups are not listed as backlogs', (await store.listSlugs()).join(',') === 'x');

  await store.remove('x');
  check('backup: removing a backlog removes its backup too', !fs.files.has('.reqforge/x.backlog.yaml.bak'));
}

console.log(`\n${pass} passed, ${fail} failed`);
process.exit(fail === 0 ? 0 : 1);
